package br.com.foursys.locadora.util;

public enum Logradouro {

	ACESSO("Acesso"),
	ACAMPAMENTO("Acampamento"),
	ACESSOLOCAL("Acesso Local"),
	ADRO("Adro"),
	ÁREAESPECIAL("Área Especial"),
	AEROPORTO("Aeroporto"),
	ALAMEDA("Alameda"),
	ANELVIÁRIO("Anel Viário"),
	ANTIGAESTRADA("Antiga Estrada"),
	ARTÉRIA("Artéria"),
	ALTO("Alto"),
	ATALHO("Atalho"),
	ÁREAVERDE("Área Verde"),
	AVENIDA("Avenida"),
	AVENIDACONTORNO("Avenida Contorno"),
	AVENIDAMARGINAL("Avenida Marginal"),
	AVENIDAMARGINALDIREITA("Avenida Marginal Direita"),
	AVENIDAMARGINALESQUERDA("Avenida Marginal Esquerda"),
	AVENIDAVELHA("Avenida Velha"),
	BALNEÁRIO("Balneário"),
	BECO("Beco"),
	BURACO("Buraco"),
	BELVEDERE("Belvedere"),
	BLOCO("Bloco"),
	BALÃO("Balão"),
	BLOCOS("Blocos"),
	BULEVAR("Bulevar"),
	BOSQUE("Bosque"),
	BOULEVARD("Boulevard"),
	BAIXA("Baixa"),
	CAIS("Cais"),
	CALÇADA("Calçada"),
	CAMINHO("Caminho"),
	CANAL("Canal"),
	CHÁCARA("Chácara"),
	CHAPADÃO("Chapadão"),
	CICLOVIA("Ciclovia"),
	CIRCULAR("Circular"),
	CONJUNTO("Conjunto"),
	CONJUNTOMUTIRÃO("Conjunto Mutirão"),
	COMPLEXOVIÁRIO("Complexo Viário"),
	COLÔNIA("Colônia"),
	COMUNIDADE("Comunidade"),
	CONDOMÍNIO("Condomínio"),
	CORREDOR("Corredor"),
	CAMPO("Campo"),
	CÓRREGO("Córrego"),
	CONTORNO("Contorno"),
	DESCIDA("Descida"),
	DESVIO("Desvio"),
	DISTRITO("Distrito"),
	ENTREBLOCO("Entre Bloco"),
	ESTRADAINTERMUNICIPAL("Estrada Intermunicipal"),
	ENSEADA("Enseada"),
	ENTRADAPARTICULAR("Entrada Particular"),
	ENTREQUADRA("Entre Quadra"),
	ESCADA("Escada"),
	ESCADARIA("Escadaria"),
	ESTRADAESTADUAL("Estrada Estadual"),
	ESTRADAVICINAL("Estrada Vicinal"),
	ESTRADADELIGAÇÃO("Estrada de Ligação"),
	ESTRADAMUNICIPAL("Estrada Municipal"),
	ESPLANADA("Esplanada"),
	ESTRADADESERVIDÃO("Estrada de Servidão"),
	ESTRADA("Estrada"),
	ESTRADAVELHA("Estrada Velha"),
	ESTRADAANTIGA("Estrada Antiga"),
	ESTAÇÃO("Estação"),
	ESTÁDIO("Estádio"),
	ESTÂNCIA("Estância"),
	ESTRADAPARTICULAR("Estrada Particular"),
	ESTACIONAMENTO("Estacionamento"),
	EVANGÉLICA("Evangélica"),
	ELEVADA("Elevada"),
	EIXOINDUSTRIAL("Eixo Industrial"),
	FAVELA("Favela"),
	FAZENDA("Fazenda"),
	FERROVIA("Ferrovia"),
	FONTE("Fonte"),
	FEIRA("Feira"),
	FORTE("Forte"),
	GALERIA("Galeria"),
	GRANJA("Granja"),
	NÚCLEOHABITACIONAL("Núcleo Habitacional"),
	ILHA("Ilha"),
	INDETERMINADO("Indeterminado"),
	ILHOTA("Ilhota"),
	JARDIM("Jardim"),
	JARDINETE("Jardinete"),
	LADEIRA("Ladeira"),
	LAGOA("Lagoa"),
	LAGO("Lago"),
	LOTEAMENTO("Loteamento"),
	LARGO("Largo"),
	LOTE("Lote"),
	MERCADO("Mercado"),
	MARINA("Marina"),
	MODULO("Modulo"),
	PROJEÇÃO("Projeção"),
	MORRO("Morro"),
	MONTE("Monte"),
	NÚCLEO("Núcleo"),
	NÚCLEORURAL("Núcleo Rural"),
	OUTEIRO("Outeiro"),
	PARALELA("Paralela"),
	PASSEIO("Passeio"),
	PÁTIO("Pátio"),
	PRAÇA("Praça"),
	PRAÇADEESPORTES("Praça de Esportes"),
	PARADA("Parada"),
	PARADOURO("Paradouro"),
	PONTA("Ponta"),
	PRAIA("Praia"),
	PROLONGAMENTO("Prolongamento"),
	PARQUEMUNICIPAL("Parque Municipal"),
	PARQUE("Parque"),
	PARQUERESIDENCIAL("Parque Residencial"),
	PASSARELA("Passarela"),
	PASSAGEM("Passagem"),
	PASSAGEMDEPEDESTRE("Passagem de Pedestre"),
	PASSAGEMSUBTERRÂNEA("Passagem Subterrânea"),
	PONTE("Ponte"),
	PORTO("Porto"),
	QUADRA("Quadra"),
	QUINTA("Quinta"),
	QUINTAS("Quintas"),
	RUA("Rua"),
	RUAINTEGRAÇÃO("Rua Integração"),
	RUADELIGAÇÃO("Rua de Ligação"),
	RUAPARTICULAR("Rua Particular"),
	RUAVELHA("Rua Velha"),
	RAMAL("Ramal"),
	RECREIO("Recreio"),
	RECANTO("Recanto"),
	RETIRO("Retiro"),
	RESIDENCIAL("Residencial"),
	RETA("Reta"),
	RUELA("Ruela"),
	RAMPA("Rampa"),
	RODOANEL("Rodo Anel"),
	RODOVIA("Rodovia"),
	ROTULA("Rotula"),
	RUADEPEDESTRE("Rua de Pedestre"),
	MARGEM("Margem"),
	RETORNO("Retorno"),
	ROTATÓRIA("Rotatória"),
	SEGUNDAAVENIDA("Segunda Avenida"),
	SITIO("Sitio"),
	SERVIDÃO("Servidão"),
	SETOR("Setor"),
	SUBIDA("Subida"),
	TRINCHEIRA("Trincheira"),
	TERMINAL("Terminal"),
	TRECHO("Trecho"),
	TREVO("Trevo"),
	TÚNEL("Túnel"),
	TRAVESSA("Travessa"),
	TRAVESSAPARTICULAR("Travessa Particular"),
	TRAVESSAVELHA("Travessa Velha"),
	UNIDADE("Unidade"),
	VIA("Via"),
	VIACOLETORA("Via Coletora"),
	VIALOCAL("Via Local"),
	VIADEACESSO("Via de Acesso"),
	VALA("Vala"),
	VIACOSTEIRA("Via Costeira"),
	VIADUTO("Viaduto"),
	VIAEXPRESSA("Via Expressa"),
	VEREDA("Vereda"),
	VIAELEVADO("Via Elevado"),
	VILA("Vila"),
	VIELA("Viela"),
	VALE("Vale"),
	VIALITORÂNEA("Via Litorânea"),
	VIADEPEDESTRE("Via de Pedestre"),
	VARIANTE("Variante"),
	ZIGUEZAGUE("Zigue-Zague");

	private String descricao;
	
	Logradouro(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
}
